### ISSUE TITLE
403 error when generating certificate using CSR with multiple SANs

### ISSUE THREAD

**Issue by lamiska** [nuxi/acme-tiny#7]
Hi, 

I am trying to generate certificate with CSR, which contains two domains in Subject Alternative Name:

*.domain.tld, domain.tld

When I set correct DNS record and try running acme script I end up with this error: 

```
Traceback (most recent call last):
  File "/usr/sbin/acme_tiny_wild.py", line 276, in <module>
    main(sys.argv[1:])
  File "/usr/sbin/acme_tiny_wild.py", line 272, in main
    dns_update_algo=dns_update_algo)
  File "/usr/sbin/acme_tiny_wild.py", line 206, in get_crt
    _send_signed_request(order['finalize'], {"csr": _b64(csr_der)}, "Error finalizing order")
  File "/usr/sbin/acme_tiny_wild.py", line 69, in _send_signed_request
    return _do_request(url, data=data.encode('utf8'), err_msg=err_msg, depth=depth)
  File "/usr/sbin/acme_tiny_wild.py", line 55, in _do_request
    raise ValueError("{0}:\nUrl: {1}\nData: {2}\nResponse Code: {3}\nResponse: {4}".format(err_msg, url, data, code, resp_data))
ValueError: Error finalizing order:
Url: https://acme-v02.api.letsencrypt.org/acme/finalize/34729933/
Data: {"protected": "...."}
Response Code: 403
Response: {
  "type": "urn:ietf:params:acme:error:unauthorized",
  "detail": "Error finalizing order :: authorizations for these names not found or expired: *.domain.tld",
  "status": 403
}
```

However running script with just CSR, which contains "*.domain.tld" in SAN, scripts end successfully and generates certificate. Do you know why I am getting this error ?

**Comment by nuxi** [comment]
*doh* I'm storing the list of pending authorizations in a way where the entries for *.domain.tld and domain.tld are the same entry. So the second one overwrites the first one and I never tell LE to verify the first one.

This is pretty obvious in the output because it tells me to create two DNS records and then only verifies one of them. I can improve this more a bit later but I've pushed a quick fix in e37c34b for now that just stores it in a list.

**Comment by lamiska** [comment]
Hi, I am not sure if this is desired behaviour, but generating certificate with two domains in SAN:

*.domain.tld, domain.tld

Still shows, two different TXT records for same domain:

```
# python acme_tiny.py --skip --account-key ./account.key --csr ./all.csr > ./test.crt
Using Let's Encrypt production CA: https://acme-v02.api.letsencrypt.org/directory
Parsing account key...
Parsing CSR...
Found domains: domain.tld, *.domain.tld
Getting directory...
Directory found!
Registering account...
Already registered!
Creating new order...
Order created!
Verifying *.domain.tld part 1...
_acme-challenge.domain.tld. 60 IN TXT kkMYXUIv0rVHoKNLRr3-CSjtaO3KFcb4GHMaqGz
Verifying domain.tld part 1...
_acme-challenge.domain.tld. 60 IN TXT hoPWdl0noa_CbJ0jU9A4yfRYWvoJZa6C3bJZ2da
Press enter to continue after updating DNS server
```

**Comment by nuxi** [comment]
Yep, thats expected. There are two different authorizations to be completed and both TXT records must be added to your DNS server.
